/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as HipaaNoticeRouteImport } from './routes/hipaa-notice'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as PatientResourcesRouteImport } from './routes/patient-resources'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaNoticeRoute = HipaaNoticeRouteImport.update({
  id: '/hipaa-notice',
  path: '/hipaa-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientResourcesRoute = PatientResourcesRouteImport.update({
  id: '/patient-resources',
  path: '/patient-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/hipaa-notice': typeof HipaaNoticeRoute
  '/insurance': typeof InsuranceRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/hipaa-notice': typeof HipaaNoticeRoute
  '/insurance': typeof InsuranceRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/hipaa-notice': typeof HipaaNoticeRoute
  '/insurance': typeof InsuranceRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/book-appointment'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/financing'
    | '/hipaa-notice'
    | '/insurance'
    | '/patient-resources'
    | '/privacy-policy'
    | '/terms'
    | '/blog/$slug'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog/'
    | '/services/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/book-appointment'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/financing'
    | '/hipaa-notice'
    | '/insurance'
    | '/patient-resources'
    | '/privacy-policy'
    | '/terms'
    | '/blog/$slug'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog'
    | '/services'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/book-appointment'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/financing'
    | '/hipaa-notice'
    | '/insurance'
    | '/patient-resources'
    | '/privacy-policy'
    | '/terms'
    | '/blog/$slug'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog/'
    | '/services/'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  FaqRoute: typeof FaqRoute
  FinancingRoute: typeof FinancingRoute
  HipaaNoticeRoute: typeof HipaaNoticeRoute
  InsuranceRoute: typeof InsuranceRoute
  PatientResourcesRoute: typeof PatientResourcesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TeamSlugRoute: typeof TeamSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa-notice': {
      id: '/hipaa-notice'
      path: '/hipaa-notice'
      fullPath: '/hipaa-notice'
      preLoaderRoute: typeof HipaaNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-resources': {
      id: '/patient-resources'
      path: '/patient-resources'
      fullPath: '/patient-resources'
      preLoaderRoute: typeof PatientResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  FaqRoute: FaqRoute,
  FinancingRoute: FinancingRoute,
  HipaaNoticeRoute: HipaaNoticeRoute,
  InsuranceRoute: InsuranceRoute,
  PatientResourcesRoute: PatientResourcesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TeamSlugRoute: TeamSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
